# Generated by Django 4.2 on 2025-11-07 14:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="img/profiles/avatar.png",
                        null=True,
                        upload_to="profiles",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("employee", "Employee"),
                            ("customer", "Customer"),
                        ],
                        default="customer",
                        max_length=50,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        default="products/default-product.png", upload_to="products"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.IntegerField(default=0)),
                ("stock", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_hot_deal", models.BooleanField(default=False)),
                ("sales_count", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="base.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Images Gallery",
                "verbose_name_plural": "Images Gallerys",
            },
        ),
        migrations.CreateModel(
            name="ManagerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("date_hired", models.DateField(auto_now_add=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("sales", "Sales"),
                            ("marketing", "Marketing"),
                            ("customer_service", "Customer Service"),
                            ("product", "Product Management"),
                            ("logistics", "Logistics & Supply Chain"),
                            ("finance", "Finance & Accounting"),
                            ("hr", "Human Resources"),
                            ("it", "Information Technology"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            (
                                "management:General Manager",
                                "General Manager (Management)",
                            ),
                            (
                                "management:Operations Manager",
                                "Operations Manager (Management)",
                            ),
                            (
                                "management:Assistant Manager",
                                "Assistant Manager (Management)",
                            ),
                            ("sales:Sales Executive", "Sales Executive (Sales)"),
                            ("sales:Account Manager", "Account Manager (Sales)"),
                            (
                                "sales:Business Development Associate",
                                "Business Development Associate (Sales)",
                            ),
                            (
                                "marketing:Digital Marketing Specialist",
                                "Digital Marketing Specialist (Marketing)",
                            ),
                            ("marketing:SEO Analyst", "SEO Analyst (Marketing)"),
                            (
                                "marketing:Social Media Manager",
                                "Social Media Manager (Marketing)",
                            ),
                            (
                                "customer_service:Customer Support Representative",
                                "Customer Support Representative (Customer Service)",
                            ),
                            (
                                "customer_service:Live Chat Agent",
                                "Live Chat Agent (Customer Service)",
                            ),
                            (
                                "customer_service:Customer Experience Supervisor",
                                "Customer Experience Supervisor (Customer Service)",
                            ),
                            (
                                "product:Product Manager",
                                "Product Manager (Product Management)",
                            ),
                            (
                                "product:Product Analyst",
                                "Product Analyst (Product Management)",
                            ),
                            (
                                "product:Merchandising Specialist",
                                "Merchandising Specialist (Product Management)",
                            ),
                            (
                                "logistics:Logistics Coordinator",
                                "Logistics Coordinator (Logistics & Supply Chain)",
                            ),
                            (
                                "logistics:Inventory Controller",
                                "Inventory Controller (Logistics & Supply Chain)",
                            ),
                            (
                                "logistics:Delivery Supervisor",
                                "Delivery Supervisor (Logistics & Supply Chain)",
                            ),
                            ("finance:Accountant", "Accountant (Finance & Accounting)"),
                            (
                                "finance:Financial Analyst",
                                "Financial Analyst (Finance & Accounting)",
                            ),
                            (
                                "finance:Billing Specialist",
                                "Billing Specialist (Finance & Accounting)",
                            ),
                            ("hr:HR Manager", "HR Manager (Human Resources)"),
                            (
                                "hr:Recruitment Officer",
                                "Recruitment Officer (Human Resources)",
                            ),
                            (
                                "hr:Training & Development Coordinator",
                                "Training & Development Coordinator (Human Resources)",
                            ),
                            (
                                "it:Backend Developer",
                                "Backend Developer (Information Technology)",
                            ),
                            (
                                "it:System Administrator",
                                "System Administrator (Information Technology)",
                            ),
                            (
                                "it:Technical Support Engineer",
                                "Technical Support Engineer (Information Technology)",
                            ),
                            (
                                "general:Administrative Assistant",
                                "Administrative Assistant (General)",
                            ),
                            (
                                "general:Office Coordinator",
                                "Office Coordinator (General)",
                            ),
                            ("general:Data Entry Clerk", "Data Entry Clerk (General)"),
                        ],
                        default="general:Administrative Assistant",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
                ),
                ("coupons_count", models.PositiveIntegerField(default=0)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(through="base.CartItem", to="base.product"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
