# Generated by Django 4.2 on 2025-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeletedEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="img/profiles/avatar.png",
                        null=True,
                        upload_to="profiles",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("position", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("date_hired", models.DateField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
